//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfOptionOneApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsMaterial
    {
        public int ID { get; set; }
        public int IDProduct { get; set; }
        public int IDMaterialShorts { get; set; }
        public int AmountMaterial { get; set; }
    
        public virtual MaterialShorts MaterialShorts { get; set; }
        public virtual Product Product { get; set; }
    }
}
