//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfOptionOneApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductsMaterial = new HashSet<ProductsMaterial>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int Articule { get; set; }
        public decimal Cost { get; set; }
        public string Image { get; set; }
        public int IDProductsType { get; set; }
        public int NumberOfPersons { get; set; }
        public int WorkshopNumber { get; set; }
    
        public virtual ProductsType ProductsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsMaterial> ProductsMaterial { get; set; }
    }
}
