//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfOptionOneApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public int INN { get; set; }
        public int IDAgentType { get; set; }
        public int IDDileveryHistory { get; set; }
    
        public virtual AgentType AgentType { get; set; }
        public virtual DileveryHistory DileveryHistory { get; set; }
    }
}
